window.BBR_PRODUCTS = [
  {
    code: "BBR-HB-001",
    name: "Handmade Luxury Pearl Beaded Handbag",
    collection: "Signature Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 8,000",
    priceUSD: "USD 35",
    status: "Made to Order",
    badge: "Premium Collection",
    featured: true,
    image: "images/product-001.jpg",
    description: "A timeless pearl beaded handbag, handcrafted bead by bead with premium high-luster pearl beads and durable monofilament nylon thread. Designed for weddings, evening events and special occasions.",
    materials: "Premium high-luster pearl-white beads; high-strength monofilament/nylon beading thread.",
    colors: "Pearl White / Ivory. Custom transparent or gold-accented beads available on request.",
    production: "2–3 business days",
    bulk: "Available on request"
  },
  {
    code: "BBR-SB-001",
    name: "Handmade Pearl Mini Crossbody / Shoulder Pouch",
    collection: "Signature Collection",
    category: "SHOULDER BAGS",
    pricePKR: "PKR 6,000",
    priceUSD: "USD 20",
    status: "Made to Order",
    badge: "Elegant Essential",
    featured: true,
    image: "images/product-002.jpg",
    description: "A compact pearl beaded crossbody/shoulder bag with a flap design, metallic magnetic closure and handcrafted beaded strap. Ideal for weddings, evenings and special occasions.",
    materials: "High-luster pearl-white beads; durable monofilament/nylon beading thread; metallic magnetic closure.",
    colors: "Pearl White / Ivory. Custom color accents available on request.",
    production: "2–3 business days",
    bulk: "Available on request"
  },
    {
    code: "BBR-PB-001",
    name: "Handmade Pearl Beaded Party Potli Bag",
    collection: "Celebration Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 10,000",
    priceUSD: "USD 36",
    status: "In Stock + Made to Order",
    badge: "Party Favorite",
    featured: true,
    image: "images/beads party.jpg.jpg",
    description: "A beautifully handcrafted pearl beaded party potli bag featuring textured floral-style beadwork, a satin inner pouch and a decorative satin ribbon bow. Designed for weddings, parties, festive occasions and elegant evening events.",
    materials: "Faux pearl beads in multiple sizes; durable clear monofilament/nylon beading thread; satin inner pouch; satin ribbon; metal hardware.",
    colors: "Beige / Pink / Off-White.",
    production: "2–3 days, depending on quantity",
    bulk: "Available for bulk orders on request"
  },
    {
    code: "BBR-PC-001",
    name: "Handmade Pearl Beaded Clutch Shoulder Bag",
    collection: "Signature Collection",
    category: "SHOULDER BAGS",
    pricePKR: "PKR 7,000",
    priceUSD: "USD 25",
    status: "In Stock + Made to Order",
    badge: "Elegant Classic",
    featured: true,
    image: "images/pearl beaded clutch.png",
    description: "A timeless pearl-beaded clutch shoulder bag handcrafted with lustrous ivory-toned beads and a matching woven shoulder strap. Its compact silhouette makes it an elegant choice for weddings, evening occasions, celebrations and special events.",
    materials: "Faux pearl beads with a glossy pearlescent finish; high-strength clear monofilament/nylon beading thread.",
    colors: "Off-White / Ivory / Cream",
    production: "2 days, depending on order quantity",
    bulk: "Available for bulk orders on request"
  },
    {
    code: "BBR-EP-001",
    name: "Handmade Pearl Beaded Evening Party Bag",
    collection: "Celebration Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 9,000",
    priceUSD: "USD 32",
    status: "In Stock + Made to Order",
    badge: "Evening Favorite",
    featured: true,
    image: "images/Handmade Pearl Beaded Evening Party Bag.jpg",
    description: "A beautifully handcrafted pearl beaded evening party bag featuring a textured pearl-bead body, matching beaded handle and elegant satin interior. Designed for weddings, evening celebrations, parties and special occasions.",
    materials: "Faux pearl beads with a glossy pearlescent finish; high-strength clear monofilament/nylon beading thread; satin interior.",
    colors: "Ivory / Cream / Off-White",
    production: "2–3 days, depending on order quantity",
    bulk: "Available for bulk orders on request"
  },
    {
    code: "BBR-MQ-001",
    name: "Handmade Mini Pearl Beaded Quinn Bag",
    collection: "Signature Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 11,000",
    priceUSD: "USD 40",
    status: "Made to Order",
    badge: "Mini Luxury",
    featured: true,
    image: "images/handmade mini quinn bag.jpg",
    description: "A refined mini pearl-beaded handbag featuring a structured silhouette and matching beaded top handle. Handcrafted bead by bead in lustrous ivory-toned pearls, this compact statement bag is designed for weddings, celebrations, evening occasions and elegant everyday moments.",
    materials: "High-luster faux-pearl acrylic/glass beads; clear high-strength monofilament nylon line woven in a structured right-angle pattern.",
    colors: "Cream / Off-White / Ivory",
    production: "2–3 days, depending on order",
    bulk: "Available on request via WhatsApp"
  },
    {
    code: "BBR-MB-001",
    name: "Handmade White Pearl Mia Beaded Bag",
    collection: "Signature Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 10,500",
    priceUSD: "USD 38",
    status: "Made to Order",
    badge: "Elegant Pearl Design",
    featured: true,
    image: "images/handmade white pearl mia beaded bag.jpg",
    description: "A delicate handmade white pearl beaded bag featuring a structured pearl-beaded body, matching handle and a soft sheer inner pouch with drawstring ribbon. Its clean ivory-white finish makes it especially suited to weddings, festive occasions, evening events and elegant gifting.",
    materials: "Faux pearls / pearl beads; woven beading thread or clear monofilament line; sheer inner pouch with drawstring ribbon.",
    colors: "White / Off-White with pearl finish.",
    production: "2–3 days, depending on order quantity",
    bulk: "Available for bulk orders on request via WhatsApp"
  },
  {
  code: "BBR-CB-001",
  name: "Handmade Crystal Bridal Beaded Clutch",
  collection: "Bridal Collection",
  category: "SHOULDER BAGS",
  pricePKR: "PKR 15,000",
  priceUSD: "USD 54",
  status: "Made to Order",
  badge: "Bridal Collection",
  featured: true,
  image: "images/handmade crystal bridal beaded wedding clutch.jpg",
  description: "A sophisticated crystal-beaded bridal clutch handcrafted with translucent faceted beads that beautifully catch and reflect the light. Featuring a structured silhouette and matching beaded shoulder strap, it is designed for brides, weddings, receptions and elegant evening occasions.",
  materials: "Translucent faceted crystal glass or acrylic beads; durable beading thread/clear monofilament line.",
  colors: "Clear / Translucent Crystal with subtle silver-white undertones.",
  production: "2–3 days, depending on order",
  bulk: "Available for bulk orders on request via WhatsApp"
},
  {
  code: "BBR-MG-001",
  name: "Handmade Mini Pearl Gifting Shoulder Bag",
  collection: "Gifting Collection",
  category: "SHOULDER BAGS",
  pricePKR: "PKR 6,500",
  priceUSD: "USD 23",
  status: "In Stock + Made to Order",
  badge: "Perfect Gift",
  featured: true,
  image: "images/handmade mini gifting beaded bag.jpg",
  description: "A charming mini pearl beaded shoulder bag designed for elegant gifting and special occasions. The compact structured body is woven with glossy pearl beads and finished with a delicate gold-tone chain strap, making it a beautiful choice for weddings, parties, festive celebrations and thoughtful gifts.",
  materials: "Faux pearl/acrylic beads; durable woven beading thread or clear monofilament line; metallic gold-tone chain strap.",
  colors: "White / Off-White pearl beads with a gold-tone chain.",
  production: "2–3 days, depending on order quantity",
  bulk: "Available for bulk orders on request via WhatsApp"
},
  {
  code: "BBR-PS-001",
  name: "Handmade Pearl Beaded Shoulder Bag",
  collection: "Signature Collection",
  category: "SHOULDER BAGS",
  pricePKR: "PKR 8,000",
  priceUSD: "USD 28",
  status: "In Stock + Made to Order",
  badge: "Pearl Classic",
  featured: true,
  image: "images/handmade pearl shoulder bag.jpg",
  description: "A timeless handmade pearl beaded shoulder bag featuring a compact structured silhouette, elegant top handle and matching shoulder strap. Its classic ivory-white pearl finish makes it a versatile choice for weddings, festive occasions, evening events and elegant everyday gifting.",
  materials: "Faux pearl / pearl acrylic beads; clear beading fishing line or durable nylon thread.",
  colors: "Ivory / White with a glossy pearl finish.",
  production: "2–3 days, depending on order quantity",
  bulk: "Available for bulk orders on request via WhatsApp"
},
  {
  code: "BBR-KC-001",
  name: "Handmade Pearl Beaded Bag Charm & Keychain Set",
  collection: "Accessories Collection",
  category: "ACCESSORIES",
  pricePKR: "PKR 1,500",
  priceUSD: "USD 5",
  status: "In Stock + Made to Order",
  badge: "Perfect Gift",
  featured: true,
  image: "images/pearl beaded bag charm keychain set.jpg",
  description: "A charming handmade pearl beaded bag charm and keychain set featuring elegant white and light-pink pearl bead designs with gold-tone key rings and lobster clasps. Perfect for decorating handbags, pouches, keys and gifting.",
  materials: "Faux pearl/acrylic pearl beads; durable woven beading thread/line; metallic gold-finish key rings with lobster clasp attachments.",
  colors: "White / Off-White, Light Pink, with Gold-tone hardware.",
  production: "2–3 days, depending on order quantity",
  bulk: "Available for bulk orders on request via WhatsApp"
},
  {
  code: "BBR-PIK-001",
  name: "Custom Pearl Initial Keychain",
  collection: "Accessories Collection",
  category: "ACCESSORIES",
  pricePKR: "PKR 1,800",
  priceUSD: "USD 6",
  status: "In Stock + Made to Order",
  badge: "Personalized Gift",
  featured: true,
  image: "images/custom initial pearl keychain.jpg",
  description: "A delicate custom pearl keychain designed with lustrous cream-toned pearls, elegant gold hardware and a pearl-white shell accent. A beautiful personalized accessory for handbags, keys, pouches and gifting.",
  materials: "Faux pearls; gold-toned metal clasp and jump rings; mother-of-pearl/acrylic shell accent; rhinestone-accented bead caps.",
  colors: "Cream / Off-White pearls; Gold hardware; Pearl White shell accent.",
  production: "2–3 days, depending on order",
  bulk: "Available on request via WhatsApp"
},
    {
    code: "BBR-TB-001",
    name: "Handmade Beaded Pearl Toggle Bracelet",
    collection: "Accessories Collection",
    category: "ACCESSORIES",
    pricePKR: "PKR 2,500",
    priceUSD: "USD 9",
    status: "In Stock + Made to Order",
    badge: "Pearl Classic",
    featured: true,
    image: "images/homemade beaded pearl toggle bracelet.jpg",
    description: "A handcrafted pearl toggle bracelet featuring luminous pearl beads arranged with delicate gold-toned spacer beads and finished with an elegant toggle clasp. A timeless accessory for everyday wear, festive occasions and thoughtful gifting.",
    materials: "Freshwater/faux pearls; gold metallic seed or spacer beads; gold-toned toggle clasp; durable jewelry wire/cord.",
    colors: "Cream / Iridescent White pearls with Gold-toned beads and clasp.",
    production: "2–3 days, depending on order quantity",
    bulk: "Available for bulk orders on request via WhatsApp"
  }
];

