window.BBR_PRODUCTS = [
  {
    code: "BBR-HB-001",
    name: "Handmade Luxury Pearl Beaded Handbag",
    collection: "Signature Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 8,000",
    priceUSD: "USD 35",
    status: "Made to Order",
    badge: "Premium Collection",
    featured: true,
    image: "images/product-001.jpg",
    description: "A timeless pearl beaded handbag, handcrafted bead by bead with premium high-luster pearl beads and durable monofilament nylon thread. Designed for weddings, evening events and special occasions.",
    materials: "Premium high-luster pearl-white beads; high-strength monofilament/nylon beading thread.",
    colors: "Pearl White / Ivory. Custom transparent or gold-accented beads available on request.",
    production: "2–3 business days",
    bulk: "Available on request"
  },
  {
    code: "BBR-SB-001",
    name: "Handmade Pearl Mini Crossbody / Shoulder Pouch",
    collection: "Signature Collection",
    category: "SHOULDER BAGS",
    pricePKR: "PKR 6,000",
    priceUSD: "USD 20",
    status: "Made to Order",
    badge: "Elegant Essential",
    featured: true,
    image: "images/product-002.jpg",
    description: "A compact pearl beaded crossbody/shoulder bag with a flap design, metallic magnetic closure and handcrafted beaded strap. Ideal for weddings, evenings and special occasions.",
    materials: "High-luster pearl-white beads; durable monofilament/nylon beading thread; metallic magnetic closure.",
    colors: "Pearl White / Ivory. Custom color accents available on request.",
    production: "2–3 business days",
    bulk: "Available on request"
  },
    {
    code: "BBR-PB-001",
    name: "Handmade Pearl Beaded Party Potli Bag",
    collection: "Celebration Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 10,000",
    priceUSD: "USD 36",
    status: "In Stock + Made to Order",
    badge: "Party Favorite",
    featured: true,
    image: "images/beads party.jpg.jpg",
    description: "A beautifully handcrafted pearl beaded party potli bag featuring textured floral-style beadwork, a satin inner pouch and a decorative satin ribbon bow. Designed for weddings, parties, festive occasions and elegant evening events.",
    materials: "Faux pearl beads in multiple sizes; durable clear monofilament/nylon beading thread; satin inner pouch; satin ribbon; metal hardware.",
    colors: "Beige / Pink / Off-White.",
    production: "2–3 days, depending on quantity",
    bulk: "Available for bulk orders on request"
  },
    {
    code: "BBR-PC-001",
    name: "Handmade Pearl Beaded Clutch Shoulder Bag",
    collection: "Signature Collection",
    category: "SHOULDER BAGS",
    pricePKR: "PKR 7,000",
    priceUSD: "USD 25",
    status: "In Stock + Made to Order",
    badge: "Elegant Classic",
    featured: true,
    image: "images/pearl beaded clutch.png",
    description: "A timeless pearl-beaded clutch shoulder bag handcrafted with lustrous ivory-toned beads and a matching woven shoulder strap. Its compact silhouette makes it an elegant choice for weddings, evening occasions, celebrations and special events.",
    materials: "Faux pearl beads with a glossy pearlescent finish; high-strength clear monofilament/nylon beading thread.",
    colors: "Off-White / Ivory / Cream",
    production: "2 days, depending on order quantity",
    bulk: "Available for bulk orders on request"
  },
    {
    code: "BBR-EP-001",
    name: "Handmade Pearl Beaded Evening Party Bag",
    collection: "Celebration Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 9,000",
    priceUSD: "USD 32",
    status: "In Stock + Made to Order",
    badge: "Evening Favorite",
    featured: true,
    image: "images/Handmade Pearl Beaded night Party Bag.jpg",
    description: "A beautifully handcrafted pearl beaded evening party bag featuring a textured pearl-bead body, matching beaded handle and elegant satin interior. Designed for weddings, evening celebrations, parties and special occasions.",
    materials: "Faux pearl beads with a glossy pearlescent finish; high-strength clear monofilament/nylon beading thread; satin interior.",
    colors: "Ivory / Cream / Off-White",
    production: "2–3 days, depending on order quantity",
    bulk: "Available for bulk orders on request"
  },
    {
    code: "BBR-MQ-001",
    name: "Handmade Mini Pearl Beaded Quinn Bag",
    collection: "Signature Collection",
    category: "HANDBAGS",
    pricePKR: "PKR 11,000",
    priceUSD: "USD 40",
    status: "Made to Order",
    badge: "Mini Luxury",
    featured: true,
    image: "images/handmade mini quinn bag.jpg",
    description: "A refined mini pearl-beaded handbag featuring a structured silhouette and matching beaded top handle. Handcrafted bead by bead in lustrous ivory-toned pearls, this compact statement bag is designed for weddings, celebrations, evening occasions and elegant everyday moments.",
    materials: "High-luster faux-pearl acrylic/glass beads; clear high-strength monofilament nylon line woven in a structured right-angle pattern.",
    colors: "Cream / Off-White / Ivory",
    production: "2–3 days, depending on order",
    bulk: "Available on request via WhatsApp"
  }
];

